### ISSUE TITLE
Documentation & Testing Improvements

### ISSUE THREAD

**Issue by acburdine** [heroku/ember-sortable#123]
As part of 1.10, I'd like to get done a few things related to documentation/testing. This issue serves as a checklist both for myself and as a comment area for anything anyone else can think needs to happen related to docs & testing.

List of things:
- [x] Add API documentation (in progress - #122)
- [ ] Improve Travis release process to auto-update the gh-pages branch
- [ ] Add code coverage via coveralls or similar
  - [ ] Based on code coverage results, improve test coverage

**Comment by jacobq** [comment]
Could you also show how to view the source code for the demos?

**Comment by acburdine** [comment]
@jacobq great idea! I'll definitely add that :)

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
